### ISSUE TITLE
 java.lang.Exception: zlib not compatible on this system

### ISSUE THREAD

**Issue by qianmuxi** [andrewhayden/archive-patcher#12] opened 2017-05-15 08:16 UTC
Android o apk25,find crash zlib not compatible on this system.
new DefaultDeflateCompatibilityWindow().isCompatible() return false

**Comment by andrewhayden** [comment] 2017-05-15 15:35
Please provide the details of the device in question: the manufacturer, model, and the exact build number of Android where the crash is occurring. With this we can try to cross-reference with AOSP and see if there is anything broken.

As a general rule, devices running Ice Cream Sandwich or later are compatible. More details on compatibility are found below:
https://github.com/andrewhayden/archive-patcher#compatibility-window

**Comment by qianmuxi** [comment] 2017-05-16 02:56
<img width="1069" alt="crash" src="https://cloud.githubusercontent.com/assets/11674768/26087807/ab1eb8ee-3a25-11e7-9ced-54e4bd13bbc3.png">
![2](https://cloud.githubusercontent.com/assets/11674768/26087879/2cfab516-3a26-11e7-87db-b5ccf9ea846b.jpg)

Android o api25,find crash zlib not compatible on this system.
new DefaultDeflateCompatibilityWindow().isCompatible() return false

**Comment by andrewhayden** [comment] 2017-05-19 06:37
Thank you for providing these details for repro. The details have been communicated to right stakeholders. I don't have any additional details to provide at this time. I'll ping the folks at Google to see if they are willing and able to update this issue appropriately.

**Comment by qianmuxi** [comment] 2017-07-03 03:04
Hello,is there any response for this problem?

**Comment by canamaria** [comment] 2017-07-12 10:23
Thank you for reporting the bug and providing the repro details! We have investigated the bug, found the root cause and are currently working towards a solution. If you have further questions please reach out to our point of contact.

**Comment by andrewhayden** [comment] 2017-07-22 18:29
The README.md file has been updated with contact information (see the bottom of the document). I'll leave this bug open and leave it to Google to resolve once the fix is available.

**Comment by qianmuxi** [comment] 2017-09-12 13:16
Thank you, this problem has been fixed.

**Comment by andrewhayden** [comment] 2017-10-17 15:19
AFAIK there is no upstreamed fix in this repository yet. @canamaria do you have any updates on an upstream fix here?

**Comment by canamaria** [comment] 2018-04-24 13:42
This issue did not require a fix in the Archive Patcher code base and was caused by [this](https://bugs.openjdk.java.net/browse/JDK-8184306) ZLIB 1.2.11 regression.

Archive Patcher's compatibility test relies on a cached Deflater which was producing corrupt output as a result of the bug above. Marking as fixed, as this should no longer be a problem.

**Comment by andrewhayden** [comment] 2018-07-07 14:12
This is a zlib regression as described by @canamaria. Upgrading or downgrading your version of Android and/or the Java runtime will most likely fix the problem. The only alternative we have is to try and detect the bug and fall back to a code path that doesn't cache the deflater/inflater instances that are being used.

**Closed by andrewhayden** 2018-07-07 14:12 UTC
Labels: Priority-High, Type-Defect

**Comment by commutescript** [comment] 2019-07-12 08:38
mac os also has this problem,  jdk is 1.7.0_80. is this project can just run on linux or Android?
