### ISSUE TITLE
Android: java.lang.IllegalStateException: setLevel cannot be called after setInput

### ISSUE THREAD

**Issue by lchad** [andrewhayden/archive-patcher#17] opened 2018-06-15 03:58 UTC
**this is the stacktrack.**

 java.lang.IllegalStateException: setLevel cannot be called after setInput
                                                                      at java.util.zip.Deflater.setLevel(Deflater.java:428)
                                                                      at com.google.archivepatcher.generator.DefaultDeflateCompressionDiviner.divineDeflateParameters(DefaultDeflateCompressionDiviner.java:172)
                                                                      at com.google.archivepatcher.generator.DefaultDeflateCompressionDiviner.divineDeflateParameters(DefaultDeflateCompressionDiviner.java:114)
                                                                      at com.google.archivepatcher.generator.PreDiffExecutor.generatePreDiffPlan(PreDiffExecutor.java:216)
                                                                      at com.google.archivepatcher.generator.PreDiffExecutor.prepareForDiffing(PreDiffExecutor.java:157)
                                                                      at com.google.archivepatcher.generator.FileByFileV1DeltaGenerator.generateDelta(FileByFileV1DeltaGenerator.java:81)
                                                                      at com.xingbianli.app.MainActivity$1$1.run(MainActivity.java:51)
                                                                      at java.lang.Thread.run(Thread.java:818)

**this is my code.**
```
 findViewById(R.id.diff).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        if (!new DefaultDeflateCompatibilityWindow().isCompatible()) {
                            System.err.println("zlib not compatible on this system");
                            System.exit(-1);
                        }
                        File oldFile = new File(old); // must be a zip archive
                        File newFile = new File(newversion); // must be a zip archive
                        Deflater compressor = new Deflater(9, true); // to compress the patch
                        try {
                            FileOutputStream patchOut = new FileOutputStream(pat);
                            DeflaterOutputStream compressedPatchOut =
                                    new DeflaterOutputStream(patchOut, compressor, 32768);
                            new FileByFileV1DeltaGenerator().generateDelta(oldFile, newFile, compressedPatchOut);
                            compressedPatchOut.finish();
                            compressedPatchOut.flush();
                        } catch (IOException e) {
                            e.printStackTrace();
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        } finally {
                            compressor.end();
                        }
                    }
                }).start();
            }
        });
```

**Comment by lchad** [comment] 2018-06-26 08:06
@andrewhayden

**Comment by andrewhayden** [comment] 2018-07-07 14:09
@lchad this appears to be a duplicate of issue 12. There was a bug in zlib 1.2.11 that caused this regression. This means that the version of zlib that you're running with is broken and should be updated, if possible; generally, updating to a newer version of Android is likely to fix this problem for you - or even downgrading, since this bug only affects a specific version of zlib.

Also from your stack trace it looks like you are trying to generate a patch on Android. While that is technically possible, the performance of patch generation is usually not well suited to mobile computing devices and in general you are better off using a server platform for patch generation.

**Comment by andrewhayden** [comment] 2018-07-07 14:15
I'll go ahead and resolve this for now; as stated in issue #12 there is no workaround without us implementing some kind of fallback logic specific to this version of zlib, which would introduce a large amount of complexity into the code to fix a very narrow problem with one specific release of zlib. While I realize this probably isn't the answer you're hoping for, I wanted to reply.

**Closed by andrewhayden** 2018-07-07 14:15 UTC
