### ISSUE TITLE
Run the demo, it has a NPE, msg is "Inflater has been closed"

### ISSUE THREAD

**Issue by commutescript** [andrewhayden/archive-patcher#138] opened 2019-07-05 13:54 UTC
it can not work well

**Comment by commutescript** [comment] 2019-07-06 07:58
> could you share some details on how you run the demo?

I have established a application module,  then copy the code in the SamplePatchApplier class into MainActivity,  after launch it show "Inflater has been closed".

**Comment by commutescript** [comment] 2019-07-06 16:57
Thank you for you reply. I have remove the DeflaterOutputStream, it still have the same NPE. It is DefaultDeflateCompressionDiviner's method--divineDeflateParameters go wrong. And i directly use  BsDiffDeltaGenerator to generate the delta, the output file is aways about 20B.

**Comment by pspencil** [comment] 2019-07-06 17:52
1. Does the NPE occur in the applier or the generator? (AFAIK,
DefaultDeflateCompressionDiviner is in the generator but you previously
said you copied the code from the sample applier).
2. If you used "BsDiffDeltaGenerator" to generate the delta, you need to
use BsDiffDeltaApplier to apply the delta.

(Also, 20 bytes for a patch seem really small, do you mind sending me your
old and new archive to test?)

**Comment by commutescript** [comment] 2019-07-07 03:09
1. NPE occur in the generator, i do not have test applier.
2. I test the generator with wexin, qq. And what's your email address, it's my honor to send old and new archive to you.

**Comment by commutescript** [comment] 2019-07-08 03:12
Old version and new version apk is posted to your email, MainActivity is also in the zip. 

Thank you for your patience！

**Comment by pspencil** [comment] 2019-07-11 10:53
Found the cause. It is due to different implementation of InflaterInputStream in android JDK.

In Android, close() ends the inflater all the time. https://chromium.googlesource.com/android_tools/+/refs/heads/master/sdk/sources/android-25/java/util/zip/InflaterInputStream.java#229

In non-Android it only closes if it is created within the InflaterInputStream. https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/util/zip/InflaterInputStream.java#L226

Since we reuse the Inflater [here](https://github.com/google/archive-patcher/blob/master/generator/src/main/java/com/google/archivepatcher/generator/DefaultDeflateCompressionDiviner.java#L173) and closes the InflaterInputStream [here](https://github.com/google/archive-patcher/blob/master/generator/src/main/java/com/google/archivepatcher/generator/DefaultDeflateCompressionDiviner.java#L224), it behaves differently on Android.

I will have to think about how to fix this.

**Comment by commutescript** [comment] 2019-07-11 13:12
Ok, thx!

**Comment by pspencil** [comment] 2019-07-15 12:55
Should be fixed by the commit.

**Closed as completed** 2019-07-15 12:55 UTC

**Comment by commutescript** [comment] 2019-07-16 06:31
It still cannot word well in the demo i post you

**Comment by commutescript** [comment] 2019-07-16 06:36
BsDiffDeltaGenerator can not generate delta well, the delta size is always  20B.

**Comment by pspencil** [comment] 2019-07-16 10:05
1. note that the commit is in the v2 branch only. 
2. I will look into the bsdiff thing.

**Comment by pspencil** [comment] 2019-07-16 10:30
For the BSDIFF thing, it seems that the task never finish. Probably it times out? Since you are generating patches on Android, it could be very slow.

**Comment by commutescript** [comment] 2019-07-16 13:24
ok, thx

**Comment by commutescript** [comment] 2019-07-16 13:35
hi, what's the difference between the master and v2,  v2 is stable？ Thank you very mach!

**Comment by pspencil** [comment] 2019-07-16 13:36
Technically speaking, master is stable. I am adding new features to v2. One of them is diffing embedded archives inside archives.

**Comment by commutescript** [comment] 2019-07-17 15:17
ok，thank you for your patient！
